"""Phase 7 — attribute vocabulary seed data extracted from listener/src/filter/constants.js.

Shared between the Alembic migration (035_attribute_vocab) and the POST /market/vocab/seed
endpoint so the seed endpoint can idempotently re-seed without duplicating the data.
"""

from __future__ import annotations

# Each entry: (category, kind, tag, canonical, [aliases])

SEED_CLOSED: list[tuple[str, str, str, str, list[str]]] = [
    # -- region (CLOSED) --
    ("region", "closed", "REGION_UK", "UK spec",
     ["UK", "🇬🇧", "UK Spec", "UK ONLY", "/B"]),
    ("region", "closed", "REGION_USA", "US spec",
     ["USA", "US Spec", "🇺🇸", "LL/A", "FOB NY", "FOB US"]),
    ("region", "closed", "REGION_JAPAN", "Japan spec",
     ["JP", "Jp", "🇯🇵"]),
    ("region", "closed", "REGION_CHINA", "China spec",
     ["China", "🇨🇳"]),
    ("region", "closed", "REGION_HONGKONG", "Hong Kong spec",
     ["HK", "🇭🇰"]),
    ("region", "closed", "REGION_INDIA", "India spec",
     ["India", "Ind", "INDIA", "🇮🇳"]),
    ("region", "closed", "REGION_EU", "EU spec",
     ["EU", "EU spec", "DE", "ZE/A", "non EU"]),
    ("region", "closed", "REGION_UAE", "UAE spec",
     ["UAE", "🇦🇪", "TRA", "Ready In Local", "Local"]),
    ("region", "closed", "REGION_KSA", "KSA spec",
     ["KSA", "Desert KSA", "Saudi"]),
    ("region", "closed", "REGION_AUSTRALIA", "Australia spec",
     ["Australia"]),
    ("region", "closed", "REGION_ANY", "Any spec",
     ["Any spec", "Mix", "we just want to buy"]),
    ("region", "closed", "SIM_ESIM", "eSIM",
     ["ESIM", "eSIM", "e-sim"]),
    ("region", "closed", "SIM_PHYSICAL", "Physical SIM",
     ["physical SIM", "HK", "UK", "AU"]),

    # -- activation (CLOSED) --
    ("activation", "closed", "ACT_NON_ACTIVE", "Non Active",
     ["Non Active", "Non-Active", "NON ACTIVE", "Non Active Stock"]),
    ("activation", "closed", "ACT_ACTIVE", "Active",
     ["Active", "A/A+"]),
    ("activation", "closed", "ACT_LOCKED", "Locked",
     ["Locked", "Brand New | Locked"]),
    ("activation", "closed", "ACT_SIMFREE", "SIM Free",
     ["Simfree", "OEM Simfree", "All OEM Simfree stock"]),
    ("activation", "closed", "ACT_OEM", "OEM",
     ["OEM", "OEM - Brand New"]),

    # -- condition (CLOSED) --
    ("condition", "closed", "COND_NEW", "New",
     ["Brand New", "New stock", "OEM Brand New", "Original Brand New"]),
    ("condition", "closed", "COND_OPEN_BOX", "Open Box",
     ["Open box", "Open box units"]),
    ("condition", "closed", "COND_GRADE_A", "Grade A",
     ["Grade A", "A/A+", "A-type"]),
    ("condition", "closed", "COND_GRADE_B", "Grade B",
     ["Grade B", "B-type"]),
    ("condition", "closed", "COND_GRADE_C", "Grade C",
     ["Grade C", "C-type"]),
    ("condition", "closed", "COND_USED_REFURB", "Used / Refurbished",
     ["used", "refurbished", "gift/refund"]),

    # -- logistics (CLOSED) --
    ("logistics", "closed", "LOC_LOCAL_READY", "Local Ready",
     ["Ready In Local", "Ready Stock", "READY IN LOCAL", "Available In Shop"]),
    ("logistics", "closed", "LOC_FZCO", "FZCO",
     ["FZCO", "Fzco", "Ready stock in Fzco"]),
    ("logistics", "closed", "LOC_OVERSEAS_DROPSHIP", "Overseas Dropship",
     ["FOB"]),
    ("logistics", "closed", "LOC_DELIVERY_DAYS", "Delivery Days",
     []),
    ("logistics", "closed", "LOC_PICKUP_STORE", "Pickup Store",
     ["Pay in-store", "Available In Shop"]),
    ("logistics", "closed", "LOC_CITY", "City",
     ["London, UK", "Hong Kong", "Dubai", "New York", "Singapore", "Shenzhen"]),

    # -- currency (CLOSED) --
    ("currency", "closed", "CUR_GBP", "GBP",
     ["GBP"]),
    ("currency", "closed", "CUR_EUR", "EUR",
     ["EUR"]),
    ("currency", "closed", "CUR_AED", "AED",
     ["AED", "AED/each", "Dhs", "Dh"]),
    ("currency", "closed", "CUR_MASKED", "Price Masked",
     ["Price on ask"]),

    # -- variant (CLOSED) --
    ("variant", "closed", "VAR_ENTERPRISE", "Enterprise Edition",
     ["Enterprise Edition", "EE"]),
    ("variant", "closed", "VAR_REGION_EAST", "Region East",
     ["Region East"]),
    ("variant", "closed", "VAR_REGION_WEST", "Region West",
     ["Region West"]),
    ("variant", "closed", "VAR_CELLULAR", "Cellular",
     ["GPS + Cellular", "5G", "4G", "Cellular"]),
    ("variant", "closed", "VAR_WIFI", "WiFi",
     ["WiFi", "BT", "Bluetooth"]),
    ("variant", "closed", "VAR_BUNDLE", "Bundle",
     ["combo", "bundle", "CaseWith"]),
    ("variant", "closed", "VAR_WATCH_SIZE", "Watch Size",
     ["40mm", "42mm", "46mm", "49mm"]),
    ("variant", "closed", "VAR_WATCH_BAND", "Watch Band",
     ["Milanese Loop", "Sport Band", "Alpine Loop", "Ocean Band", "Trail Loop"]),

    # -- risk (CLOSED) — RISK_PATTERNS minus TRUST_* --
    ("risk", "closed", "RISK_FREELANCER", "Freelancer",
     []),
    ("risk", "closed", "RISK_PRICE_MASKED", "Price Masked",
     ["best price only"]),
    ("risk", "closed", "RISK_SALEABILITY", "Saleability",
     []),

    # -- trust (CLOSED) — TRUST_HAS_* from RISK_PATTERNS --
    ("trust", "closed", "TRUST_HAS_COMPANY", "Has Company",
     ["LLC", "L.L.C", "Electronics LLC", "Electronics Trading", "Computer Technology"]),
    ("trust", "closed", "TRUST_HAS_OFFICE", "Has Office",
     ["Pay in-store", "Available In Shop"]),

    # -- side (CLOSED) — intent/side labels --
    ("side", "closed", "SIDE_BUY", "Buy",
     ["WTB", "Want to buy", "Looking to buy", "Looking for", "buying", "buyer"]),
    ("side", "closed", "SIDE_SELL", "Sell",
     ["WTS", "Want to sell", "Selling", "for sale", "seller"]),
]

SEED_COLOR: list[tuple[str, str, str, str, list[str]]] = [
    ("color", "open", "Black", "Black", ["black", "bank", "blk", "🖤"]),
    ("color", "open", "White", "White", ["white", "wht", "🤍"]),
    ("color", "open", "Blue", "Blue", ["blue", "blu", "💙"]),
    ("color", "open", "Deep Blue", "Deep Blue", ["deep blue"]),
    ("color", "open", "Sky Blue", "Sky Blue", ["sky blue"]),
    ("color", "open", "Cobalt Violet", "Cobalt Violet", ["cobalt violet"]),
    ("color", "open", "Violet", "Violet", ["violet", "violett"]),
    ("color", "open", "Silver", "Silver", ["silver", "siilver", "slvr"]),
    ("color", "open", "Grey", "Grey", ["grey", "gray", "space gray", "graphite"]),
    ("color", "open", "Navy", "Navy", ["navy"]),
    ("color", "open", "Mint", "Mint", ["mint"]),
    ("color", "open", "Olive", "Olive", ["olive"]),
    ("color", "open", "Lavender", "Lavender", ["lavender", "levander"]),
    ("color", "open", "Sage", "Sage", ["sage"]),
    ("color", "open", "Lilac", "Lilac", ["lilac"]),
    ("color", "open", "Icy Blue", "Icy Blue", ["icy blue", "icyblue"]),
    ("color", "open", "Pink", "Pink", ["pink"]),
    ("color", "open", "Green", "Green", ["green", "light green"]),
    ("color", "open", "Yellow", "Yellow", ["yellow", "💛"]),
    ("color", "open", "Gold", "Gold", ["gold", "rose gold"]),
    ("color", "open", "Orange", "Orange", ["orange", "cosmic orange", "🍊"]),
    ("color", "open", "Midnight", "Midnight", ["midnight"]),
    ("color", "open", "Starlight", "Starlight", ["starlight"]),
    ("color", "open", "Cream", "Cream", ["cream"]),
    ("color", "open", "Desert", "Desert", ["desert"]),
    ("color", "open", "Natural", "Natural", ["natural"]),
    ("color", "open", "Titanium Black", "Titanium Black", ["titanium black"]),
    ("color", "open", "Titanium Grey", "Titanium Grey", ["titanium grey", "titanium gray"]),
    ("color", "open", "Titanium Silver", "Titanium Silver", ["titanium silver"]),
    ("color", "open", "Titanium Icyblue", "Titanium Icyblue", ["titanium icyblue", "titanium icy blue"]),
    ("color", "open", "Titanium Jetblack", "Titanium Jetblack", ["titanium jetblack", "titanium jet black"]),
    ("color", "open", "Titanium Silverblue", "Titanium Silverblue", ["titanium silverblue", "titanium silver blue"]),
    ("color", "open", "Titanium Blue", "Titanium Blue", ["titanium blue"]),
    ("color", "open", "Titanium Whitesilver", "Titanium Whitesilver", ["titanium whitesilver", "titanium white silver"]),
    ("color", "open", "Blue/Silver Shadow", "Blue/Silver Shadow", ["blue/silver shadow", "silver shadow"]),
    ("color", "open", "Obsidian", "Obsidian", ["obsidian"]),
    ("color", "open", "Moonstone", "Moonstone", ["moonstone"]),
    ("color", "open", "Teal", "Teal", ["teal"]),
    ("color", "open", "Purple", "Purple", ["purple", "💜"]),
]

SEED_BRAND: list[tuple[str, str, str, str, list[str]]] = [
    # Apple
    ("brand", "open", "apple", "Apple", ["apple"]),
    ("brand", "open", "iphone", "iPhone", ["iphone 17", "iphone 16", "iphone 15", "iphone 14"]),
    ("brand", "open", "iphone 17 pro max", "iPhone 17 Pro Max", ["17 pro max", "17PM", "17 pro max", "iphone 17"]),
    ("brand", "open", "iphone 17 pro", "iPhone 17 Pro", ["17 pro", "17P"]),
    ("brand", "open", "iphone 17", "iPhone 17", []),
    ("brand", "open", "iphone 16 pro max", "iPhone 16 Pro Max", ["16 pro max", "16PM"]),
    ("brand", "open", "iphone 16 pro", "iPhone 16 Pro", ["16 pro", "16P"]),
    ("brand", "open", "iphone 16", "iPhone 16", []),
    ("brand", "open", "iphone 16e", "iPhone 16e", ["16e"]),
    ("brand", "open", "ipad", "iPad", []),
    ("brand", "open", "macbook", "MacBook", []),
    ("brand", "open", "airpods", "AirPods", ["AirPod", "airpods", "airpod"]),
    ("brand", "open", "airpods max", "AirPods Max", []),
    ("brand", "open", "apple watch", "Apple Watch", []),
    ("brand", "open", "apple pencil", "Apple Pencil", []),
    ("brand", "open", "magic mouse", "Magic Mouse", []),
    ("brand", "open", "airtag", "AirTag", []),
    # Samsung
    ("brand", "open", "samsung", "Samsung", []),
    ("brand", "open", "galaxy", "Galaxy", []),
    ("brand", "open", "s25", "S25", ["S25+", "S25 FE", "S25 Edge"]),
    ("brand", "open", "s25 ultra", "S25 Ultra", []),
    ("brand", "open", "s26", "S26", ["S26+", "S26 Ultra"]),
    ("brand", "open", "a16", "A16", []),
    ("brand", "open", "a17", "A17", []),
    ("brand", "open", "a26", "A26", []),
    ("brand", "open", "a27", "A27", []),
    ("brand", "open", "a37", "A37", []),
    ("brand", "open", "a56", "A56", []),
    ("brand", "open", "a57", "A57", []),
    ("brand", "open", "z flip7", "Z Flip7", ["Flip7 FE"]),
    ("brand", "open", "z fold7", "Z Fold7", []),
    ("brand", "open", "tri fold", "Tri Fold", []),
    ("brand", "open", "tab a11", "Tab A11", ["Tab A11+"]),
    ("brand", "open", "tab s10", "Tab S10", ["Tab S10+"]),
    ("brand", "open", "tab s11 ultra", "Tab S11 Ultra", []),
    ("brand", "open", "buds3", "Buds3", ["Buds4", "Buds"]),
    ("brand", "open", "watch 7", "Watch 7", []),
    ("brand", "open", "watch 8", "Watch 8", []),
    ("brand", "open", "xcover", "XCover", []),
    # Non-target brands
    ("brand", "open", "google", "Google", []),
    ("brand", "open", "pixel", "Pixel", []),
    ("brand", "open", "fitbit", "Fitbit", []),
    ("brand", "open", "xiaomi", "Xiaomi", []),
    ("brand", "open", "redmi", "Redmi", []),
    ("brand", "open", "oneplus", "OnePlus", []),
    ("brand", "open", "nord", "Nord", []),
    ("brand", "open", "oppo", "Oppo", []),
    ("brand", "open", "realme", "realme", []),
    ("brand", "open", "motorola", "Motorola", ["Moto"]),
    ("brand", "open", "nokia", "Nokia", []),
    ("brand", "open", "honor", "Honor", []),
    ("brand", "open", "huawei", "Huawei", []),
    ("brand", "open", "nothing", "Nothing", []),
    ("brand", "open", "fairphone", "Fairphone", []),
    ("brand", "open", "gigaset", "Gigaset", []),
    ("brand", "open", "cat", "CAT", []),
    ("brand", "open", "mobitel", "Mobitel", []),
    ("brand", "open", "dji", "DJI", []),
    ("brand", "open", "osmo", "Osmo", []),
    ("brand", "open", "gopro", "GoPro", []),
    ("brand", "open", "kodak", "Kodak", []),
    ("brand", "open", "charmera", "Charmera", []),
    ("brand", "open", "whoop", "Whoop", []),
    ("brand", "open", "starlink", "Starlink", []),
    ("brand", "open", "ps5", "PS5", []),
    ("brand", "open", "xbox", "Xbox", []),
    ("brand", "open", "amazon", "Amazon", []),
    ("brand", "open", "fire stick", "Fire Stick", []),
    ("brand", "open", "asus", "ASUS", []),
    ("brand", "open", "zenbook", "Zenbook", []),
    ("brand", "open", "dell", "Dell", []),
    ("brand", "open", "lenovo", "Lenovo", []),
    ("brand", "open", "ideapad", "IdeaPad", []),
    ("brand", "open", "nvidia", "NVIDIA", []),
    ("brand", "open", "rtx", "RTX", []),
    ("brand", "open", "air conditioner", "Air Conditioner", ["BTU"]),
]

SEED_STORAGE: list[tuple[str, str, str, str, list[str]]] = [
    ("storage", "open", "STORAGE_64GB", "64GB", ["64 GB", "64gb", "64 gb"]),
    ("storage", "open", "STORAGE_128GB", "128GB", ["128 GB", "128gb", "128 gb"]),
    ("storage", "open", "STORAGE_256GB", "256GB", ["256 GB", "256gb", "256 gb"]),
    ("storage", "open", "STORAGE_512GB", "512GB", ["512 GB", "512gb", "512 gb"]),
    ("storage", "open", "STORAGE_1TB", "1TB", ["1 TB", "1tb", "1 tb"]),
    ("storage", "open", "STORAGE_2TB", "2TB", ["2 TB", "2tb", "2 tb"]),
]

ALL_SEED_ENTRIES: list[tuple[str, str, str, str, list[str]]] = (
    SEED_CLOSED + SEED_COLOR + SEED_BRAND + SEED_STORAGE
)
